using CaseNet.Abstractions;

namespace CaseNet.Example;

public class GetTodoList
{
    public GetTodoList(int[] ids)
    {
        Ids = ids;
    }

    public int[] Ids { get; }
}

/// <summary>
///     Example use case
///     Class implements IUseCase
///     this class is a regular class
///     with arbitrary constructor parameters
///     Source generator should append generated interface
/// </summary>
public sealed class GetTodoListUseCase : IUseCase<GetTodoList, IReadOnlyCollection<Todo>>
{
    private readonly IServiceProvider _serviceProvider;

    public GetTodoListUseCase(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }

    public Task<IReadOnlyCollection<Todo>> ExecuteAsync(GetTodoList request, CancellationToken ct) =>
        throw new NotImplementedException();
}

/////////////////////////////// GENERATION PART ////////////////////////////////////

// /// <summary>
// /// Generated marker interface
// /// This interface should be generated by source generator
// /// </summary>
// public interface IGetTodoListUseCase
// {
//     Task<IReadOnlyCollection<Todo>> ExecuteAsync(
//         GetTodoList request,
//         CancellationToken ct);
// }
//
// /// <summary>
// /// Generated interactor class
// /// This generated class is a glue that combines behaviors with UseCase 
// /// </summary>
// public class GetTodoListInteractor : IGetTodoListUseCase
// {
//     /// <summary>
//     /// Wrapped UseCase
//     /// </summary>
//     private readonly GetTodoListUseCase _inner;
//     
//     /// <summary>
//     /// Behaviors registered in service collection
//     /// </summary>
//     private readonly IUseCaseBehavior<GetTodoList, IReadOnlyCollection<Todo>>[] _behaviors;
//
//     public GetTodoListInteractor(
//         GetTodoListUseCase inner,
//         IEnumerable<IUseCaseBehavior<GetTodoList, IReadOnlyCollection<Todo>>> behaviors)
//     {
//         _inner = inner;
//         _behaviors = behaviors as IUseCaseBehavior<GetTodoList, IReadOnlyCollection<Todo>>[]
//                      ?? behaviors.ToArray();
//     }
//
//     public Task<IReadOnlyCollection<Todo>> ExecuteAsync(
//         GetTodoList request,
//         CancellationToken ct)
//     {
//         var context = new InteractorContext<GetTodoList, IReadOnlyCollection<Todo>>(
//             _inner,
//             _behaviors);
//
//         return context.NextAsync(request, ct);
//     }
//     
//     [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
//     public static IServiceCollection RegisterInteractor(
//         IServiceCollection services,
//         ServiceLifetime lifetime = ServiceLifetime.Scoped
//     )
//     {
//         services.Add(new ServiceDescriptor(typeof(IGetTodoListUseCase), typeof(GetTodoListInteractor), lifetime));
//         services.Add(new ServiceDescriptor(typeof(GetTodoListUseCase), typeof(GetTodoListUseCase), lifetime));
//         return services;
//     }
// }